- name: Get the basics setup on linux machines
  hosts: managers
  vars_files: secrets.yml
  become: true
  tasks:
    - name: Place SSH Config File
      ansible.builtin.include_tasks: tasks/sshconfig.yml
    - name: Create production directories
      ansible.builtin.file:
        path: "{{ home_dir }}/{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"
      loop:
        - code
        - content
    - name: Manage Off Air Card
      ansible.builtin.include_tasks: tasks/offair.yml
  roles:
    - elliotweiser.osx-command-line-tools
    - geerlingguy.mac.homebrew
    - geerlingguy.mac.mas
