- name: Raspberry Pi Configurations
  hosts: raspberrypi
  vars_files: secrets.yml
  become: true
  tasks:
    - name: Configure Raspberry Pi
      ansible.builtin.include_tasks: tasks/rpi.yml

- name: Get the basics setup on linux machines
  hosts: linux
  vars_files: secrets.yml
  become: true
  tasks:
    - name: Basic Setup steps
      ansible.builtin.include_tasks: tasks/linux.yml
    - name: Service scripts
      ansible.builtin.include_tasks: tasks/sysmenu.yml
    - name: Create production directories
      ansible.builtin.file:
        path: "{{ home_dir }}/{{ item }}"
        state: directory
        owner: admin
        group: admin
        mode: "0755"
      loop:
        - code
        - content
    - name: Manage Off Air Card
      ansible.builtin.include_tasks: tasks/offair.yml
    - name: Manage Background Card
      ansible.builtin.include_tasks: tasks/desktop.yml
    - name: Manage Stream Return
      ansible.builtin.include_tasks: tasks/streamreturn.yml

  roles:
    - role: geerlingguy.security
    - role: artis3n.tailscale

  handlers:
    - name: Restart X11
      ansible.builtin.command: "systemctl restart lightdm"
      become: yes
      ignore_errors: yes

    - name: Restart LXDE
      ansible.builtin.command: "pkill -HUP pcmanfm"
      become_user: "{{ ansible_user }}"
