- name: Get the basics setup on linux machines
  hosts: linux
  vars_files: secrets.yml
  become: true
  tasks:
    - name: Basic Setup steps
      ansible.builtin.include_tasks: tasks/linux.yml
    - name: Service scripts
      ansible.builtin.include_tasks: tasks/sysmenu.yml
    - name: Create production directories
      ansible.builtin.file:
        path: "{{ home_dir }}/{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: server
        mode: "0755"
      loop:
        - code
        - content
    - name: Manage Off Air Card
      ansible.builtin.include_tasks: tasks/offair.yml
    - name: Manage Background Card
      ansible.builtin.include_tasks: tasks/background.yml
  roles:
    - role: geerlingguy.security
