- name: Remove existing Background Card
  ansible.builtin.file:
    path: "{{ home_dir }}/content/BGCard.png"
    state: absent

- name: Place Background Card
  ansible.builtin.template:
    src: files/BGCard.png
    dest: "{{ home_dir }}/content/BGCard.png"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  ignore_errors: false
