---
- name: Determine Homebrew ownership variables
  ansible.builtin.set_fact:
    homebrew_user: "{{ homebrew_user | default(ansible_user_id) }}"
    homebrew_group: "{{ homebrew_group | default(ansible_user_gid) }}"

# Homebrew setup prerequisites.
- name: Ensure Homebrew parent directory has correct permissions (M1).
  ansible.builtin.file:
    path: "{{ homebrew_prefix }}"
    owner: "{{ homebrew_user }}"
    state: directory
  become: true
  when: ansible_machine == 'arm64'

- name: Ensure Homebrew parent directory has correct permissions (Intel).
  when: ansible_machine == 'x86_64'
  block:
    - name: Ensure Homebrew parent directory has correct permissions (MacOS >= 10.13).
      ansible.builtin.file:
        path: "{{ homebrew_prefix }}"
        owner: root
        state: directory
      become: true
      when: "ansible_distribution_version is version('10.13', '>=')"

    - name: Ensure Homebrew parent directory has correct permissions (MacOS < 10.13).
      ansible.builtin.file:
        path: "{{ homebrew_prefix }}"
        owner: root
        group: admin
        state: directory
        mode: "0775"
      become: true
      when: "ansible_distribution_version is version('10.13', '<')"

- name: Check if homebrew already exists.
  ansible.builtin.stat:
    path: "{{ homebrew_brew_bin_path }}/brew"
  register: pre_installed_brew

- name: Ensure Homebrew directory exists.
  ansible.builtin.file:
    path: "{{ homebrew_install_path }}"
    owner: "{{ homebrew_user }}"
    group: "{{ homebrew_group }}"
    state: directory
    mode: "0775"
  become: true

# Clone Homebrew.
- name: Ensure Homebrew is installed.
  ansible.builtin.git:
    repo: "{{ homebrew_repo }}"
    version: master
    dest: "{{ homebrew_install_path }}"
    update: false
    depth: 1
  become: true
  become_user: "{{ homebrew_user }}"
  when: not pre_installed_brew.stat.exists

# Adjust Homebrew permissions.
- name: Ensure proper permissions and ownership on homebrew_brew_bin_path dirs.
  ansible.builtin.file:
    path: "{{ homebrew_brew_bin_path }}"
    state: directory
    owner: "{{ homebrew_user }}"
    group: "{{ homebrew_group }}"
    mode: "0775"
  become: true

- name: Ensure proper ownership on homebrew_install_path subdirs.
  ansible.builtin.file:
    path: "{{ homebrew_install_path }}"
    state: directory
    owner: "{{ homebrew_user }}"
    group: "{{ homebrew_group }}"
    recurse: true
    follow: false
  become: true

# Place brew binary in proper location and complete setup.
- name: Check if homebrew binary is already in place.
  ansible.builtin.stat:
    path: "{{ homebrew_brew_bin_path }}/brew"
  register: homebrew_binary
  check_mode: false

- name: Symlink brew to homebrew_brew_bin_path.
  ansible.builtin.file:
    src: "{{ homebrew_install_path }}/bin/brew"
    dest: "{{ homebrew_brew_bin_path }}/brew"
    state: link
  when: not homebrew_binary.stat.exists
  become: true

- name: Add missing folder if not on Apple-chipset
  set_fact:
    homebrew_folders_base: "{{ homebrew_folders_base + ['Homebrew'] }}"
  when: ansible_machine != 'arm64'

- name: Ensure proper homebrew folders are in place.
  ansible.builtin.file:
    path: "{{ homebrew_prefix }}/{{ item }}"
    state: directory
    owner: "{{ homebrew_user }}"
    group: "{{ homebrew_group }}"
  become: true
  loop: "{{ homebrew_folders_base + homebrew_folders_additional }}"

- name: Collect package manager fact.
  ansible.builtin.setup:
    filter: ansible_pkg_mgr

- name: Perform brew installation.
  # Privilege escalation is only required for inner steps when
  # the `homebrew_user` doesn't match the `ansible_user_id`
  become: "{{ (homebrew_user != ansible_user_id) | bool }}"
  become_user: "{{ homebrew_user }}"
  block:
    - name: Force update brew after installation.
      ansible.builtin.command: "{{ homebrew_brew_bin_path }}/brew update --force"
      when: not pre_installed_brew.stat.exists

    - name: Where is the cache?
      ansible.builtin.command: "{{ homebrew_brew_bin_path }}/brew --cache"
      register: homebrew_cache_path
      changed_when: false
      check_mode: false
