- name: Remove existing Off Air Card
  ansible.builtin.file:
    path: "{{ home_dir }}/content/OffAirCard.png"
    state: absent

- name: Place Off Air Card
  ansible.builtin.copy:
    src: files/OffAirCard.png
    dest: "{{ home_dir }}/content/OffAirCard.png"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user_group }}"
    mode: "0755"
  ignore_errors: false
