---
- name: Remove existing SSH config file
  ansible.builtin.file:
    path: "{{ home_dir }}/.ssh/config"
    state: absent

- name: Create SSH config file
  ansible.builtin.template:
    src: templates/sshconfig.j2
    dest: "{{ home_dir }}/.ssh/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  ignore_errors: false
