- name: Install Snap Packages
  community.general.snap:
    name:
      - core

- name: Ensure snapd service is restarted if snapd is installed
  service:
    name: snapd
    state: restarted
  when: "'snapd' in ansible_facts.packages"

- name: Install Snap Packages
  community.general.snap:
    name:
      - ubuntu-frame

- name: Add DISPLAY environment variable to .bashrc
  lineinfile:
    path: "/home/{{ linux_ansible_user }}/.bashrc"
    line: 'export DISPLAY=:0'
    state: present
  become_user: "{{ linux_ansible_user }}"

- name: Add XDG_RUNTIME_DIR environment variable to .bashrc
  lineinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    line: 'export XDG_RUNTIME_DIR=/run/user/1000'
    state: present
  become_user: "{{ linux_ansible_user }}"

- name: Add WAYLAND_DISPLAY environment variable to .bashrc
  lineinfile:
    path: "/home/{{ linux_ansible_user }}/.bashrc"
    line: 'export WAYLAND_DISPLAY=wayland-0'
    state: present
  become_user: "{{ linux_ansible_user }}"
