name: Check Ansible Secrets Encryption

on:
  push:
    paths:
      - secrets.yml
  pull_request:
    paths:
      - secrets.yml

jobs:
  verify_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify that secrets.yml is encrypted
        run: |
          if ! grep -q 'ANSIBLE_VAULT' secrets.yml; then
            echo "Error: secrets.yml is not encrypted. Please encrypt it using ansible-vault."
            exit 1
          fi
