name: Convert Markdown to DOCX

on:
  push:
    paths:
      - README.md

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Convert README.md to DOCX file
        run: pandoc README.md -o README.docx

      - name: Upload DOC file as artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: readme-docx
          path: README.docx
          overwrite: true
